# Generated by Django 3.2.16 on 2023-06-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Каталог товаров',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('number', models.IntegerField(default=0, verbose_name='Номер закупки')),
                ('comment', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закупки')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('cost_price_RUB', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Себестоимость в руб.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.catalog', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
