# Generated by Django 3.2.16 on 2023-06-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Каталог товаров',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.CreateModel(
            name='Client_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(default='ФЛ', max_length=256, verbose_name='Тип покупателя')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Тип покупателя',
                'verbose_name_plural': 'Типы покупателей',
            },
        ),
        migrations.CreateModel(
            name='Receiving_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256, verbose_name='Способ получения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
            },
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256, verbose_name='Способ оплаты')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('order_number', models.IntegerField(default=0, verbose_name='Номер закупки')),
                ('order_date', models.DateTimeField(blank=True, verbose_name='Дата закупки')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('product_list', models.TextField(blank=True, verbose_name='Cостав закупки')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения закупки')),
                ('comment', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('ordering_price_RMB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена закупки в юанях')),
                ('cost_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Себестоимость в руб.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('order_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_date', to='app.orders', verbose_name='Дата закупки')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_number', to='app.orders', verbose_name='Номер закупки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='app.catalog', verbose_name='Товар')),
                ('received_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_received_date', to='app.orders', verbose_name='Дата получения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('selling_price_RUB', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена продажи в руб.')),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.client_type', verbose_name='Тип покупателя')),
                ('cost_price_RUB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_cost_price_RUB', to='app.orderdetail', verbose_name='Себестоимость в рублях')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('order_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_date', to='app.orders')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_number', to='app.orders')),
                ('ordering_price_RMB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_ordering_price_RMB', to='app.orderdetail', verbose_name='Цена закупки в юанях')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.payment_type', verbose_name='Способ оплаты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.catalog', verbose_name='Наименование товара')),
                ('received_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_received_date', to='app.orders')),
                ('receiving_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.receiving_type', verbose_name='Тип получения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order_date', 'product'),
            },
        ),
    ]
