# Generated by Django 3.2.16 on 2023-07-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена по прайсу, руб.')),
                ('target_last_order_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена от последней закупки, руб.')),
                ('target_current_RMB_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена от курса, руб.')),
                ('market_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Рыночная цена, руб.')),
                ('order_price_RMB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена закупки в юанях.')),
                ('image', models.ImageField(blank=True, upload_to='app_images', verbose_name='Фото')),
                ('length', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Длина в см')),
                ('width', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Ширина в см')),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Высота в см')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True, verbose_name='Вес в кг')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Каталог товаров',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.CreateModel(
            name='Client_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(default='ФЛ', max_length=256, verbose_name='Тип покупателя')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Тип покупателя',
                'verbose_name_plural': 'Типы покупателей',
            },
        ),
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=12.5, max_digits=5, verbose_name='Биржевой курс валюты (китайский юань)')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Средние издержки на доставку, %')),
                ('markup_128', models.IntegerField(default=25, verbose_name='Наценка для товаров с себестом более 128к, %')),
                ('markup_64', models.IntegerField(default=30, verbose_name='Наценка для товаров с себестом более 64к, %')),
                ('markup_32', models.IntegerField(default=35, verbose_name='Наценка для товаров с себестом более 32к, %')),
                ('markup_16', models.IntegerField(default=40, verbose_name='Наценка для товаров с себестом более 16к, %')),
                ('markup_8', models.IntegerField(default=50, verbose_name='Наценка для товаров с себестом более 8к, %')),
                ('markup_4', models.IntegerField(default=70, verbose_name='Наценка для товаров с себестом более 4к, %')),
                ('markup_2', models.IntegerField(default=90, verbose_name='Наценка для товаров с себестом более 2к, %')),
                ('markup_0', models.IntegerField(default=120, verbose_name='Наценка для товаров с себестом менее 2к, %')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=256, verbose_name='Способ оплаты')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Receiving_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=256, verbose_name='Способ получения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sale_number', models.IntegerField(default=0, verbose_name='Номер продажи')),
                ('sale_date', models.DateTimeField(blank=True, verbose_name='Дата продажи')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество наименований товаров')),
                ('product_list', models.TextField(blank=True, verbose_name='Cостав продажи')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена проджаи')),
                ('client_name', models.CharField(blank=True, default='Покупатель', max_length=256, null=True, verbose_name='Имя покупателя')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.client_type', verbose_name='Тип покупателя')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.payment_type', verbose_name='Способ оплаты')),
                ('receiving_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.receiving_type', verbose_name='Тип получения')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-sale_number'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('sale_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена продажи')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='app.catalog', verbose_name='Товар')),
                ('sale_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail_sale_date', to='app.sales', verbose_name='Дата продажи')),
                ('sale_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail_sale_number', to='app.sales', verbose_name='Номер продажи')),
            ],
            options={
                'verbose_name': 'Детали продаж',
                'verbose_name_plural': 'Детали продаж',
                'ordering': ['-sale_number'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order_number', models.IntegerField(default=0, verbose_name='Номер закупки')),
                ('order_date', models.DateTimeField(blank=True, verbose_name='Дата закупки')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('product_list', models.TextField(blank=True, verbose_name='Cостав закупки')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Себестоимость закупки')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения закупки')),
                ('comment', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество единиц товаров')),
                ('ordering_price_RMB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена закупки в юанях')),
                ('cost_price_RUB', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Себестоимость в руб.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('order_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_date', to='app.orders', verbose_name='Дата закупки')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order_number', to='app.orders', verbose_name='Номер закупки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='app.catalog', verbose_name='Товар')),
                ('received_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_received_date', to='app.orders', verbose_name='Дата получения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Маржа, руб.')),
                ('markup', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Наценка, %')),
                ('days_in_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Дней на складе')),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_client_type', to='app.sales', verbose_name='Тип покупателя')),
                ('cost_price_RUB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_cost_price_RUB', to='app.orderdetail', verbose_name='Себестоимость в рублях')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('order_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_date', to='app.orders')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_number', to='app.orders')),
                ('ordering_price_RMB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_ordering_price_RMB', to='app.orderdetail', verbose_name='Цена закупки в юанях')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_payment_type', to='app.sales', verbose_name='Способ оплаты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.orderdetail', verbose_name='Наименование товара')),
                ('received_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_received_date', to='app.orders')),
                ('receiving_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receiving_type', to='app.sales', verbose_name='Тип получения')),
                ('sale_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_sale_date', to='app.sales', verbose_name='Дата продажи')),
                ('sale_price_RUB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_sale_price_RUB', to='app.saledetail', verbose_name='Цена продажи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order_date', 'product'),
            },
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('sale_number',), name='Unique sale_number'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.UniqueConstraint(fields=('order_number',), name='Unique order_number'),
        ),
    ]
