# Generated by Django 3.2.16 on 2023-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goods_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Себестоимость закупки'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.UniqueConstraint(fields=('order_number',), name='Unique order_number'),
        ),
    ]
