# Generated by Django 3.2.16 on 2023-07-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230716_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price_RUB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.catalog', verbose_name='Цена по прайсу'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client_contact',
            field=models.CharField(max_length=256, null=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.client_type', verbose_name='Тип покупателя'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.payment_type', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receiving_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='app.receiving_type', verbose_name='Тип получения'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(verbose_name='Дата продажи'),
        ),
    ]
