# Generated by Django 3.2.16 on 2023-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230718_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=12.5, max_digits=7, verbose_name='Биржевой курс валюты (китайский юань)'),
        ),
    ]
