# Generated by Django 3.2.16 on 2023-07-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_forstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forstock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forstock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='forstock',
            name='is_published',
        ),
    ]
