# Generated by Django 3.2.16 on 2023-07-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230702_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Высота в см'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='app_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Длина в см'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='market_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Рыночная цена, руб.'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена по прайсу, руб.'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='target_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена, руб.'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True, verbose_name='Вес в кг'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Ширина в см'),
        ),
    ]
