# Generated by Django 3.2.16 on 2023-09-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sales_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cash',
            field=models.BooleanField(default=True, verbose_name='Касса'),
        ),
    ]
