# Generated by Django 3.2.16 on 2023-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230704_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Высота в см'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Длина в см'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Вес в кг'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Ширина в см'),
        ),
    ]
