# Generated by Django 3.2.16 on 2023-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orders_unique order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='postamat',
            field=models.BooleanField(default=False, verbose_name='Постамат'),
        ),
    ]
