# Generated by Django 3.2.16 on 2023-10-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sales_postamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='postamat',
        ),
    ]
