# Generated by Django 3.2.16 on 2024-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_sales_postamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='market_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Рыночная цена, руб.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='order_price_RMB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена закупки в юанях.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена по прайсу, руб.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='target_current_RMB_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Расчетная цена от курса, руб.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='target_last_order_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Расчетная цена от последней закупки, руб.'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Маржа, руб.'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='markup',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Наценка, %'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='cost_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость в руб.'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='ordering_price_RMB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена закупки в юанях'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость закупки'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
    ]
