# Generated by Django 3.2.16 on 2024-10-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240606_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='received',
            field=models.BooleanField(blank=True, default=False, verbose_name='Получен'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sn_number',
            field=models.TextField(blank=True, verbose_name='S/n номер'),
        ),
    ]
