# Generated by Django 3.2.16 on 2023-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sales_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client_name',
            field=models.CharField(blank=True, default='Покупатель', max_length=256, null=True, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена проджаи'),
        ),
    ]
