# Generated by Django 3.2.16 on 2024-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20241012_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='received',
            field=models.BooleanField(blank=True, null=True, verbose_name='Получен'),
        ),
    ]
