# Generated by Django 3.2.16 on 2023-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230706_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='days_in_stock',
            field=models.IntegerField(default=0, verbose_name='Дней на складе'),
        ),
        migrations.AddField(
            model_name='goods',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Маржа, руб.'),
        ),
        migrations.AddField(
            model_name='goods',
            name='markup',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Наценка, %'),
        ),
    ]
