# Generated by Django 3.2.16 on 2023-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230707_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXCHANGE_RATE', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Биржевой курс валюты (китайский юань)')),
                ('DELIVERY_COSTS', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Средние издержки на доставку, %')),
                ('MARKUP_100', models.IntegerField(default=30, verbose_name='Наценка для товаров с себестом более 100к, %')),
                ('MARKUP_50', models.IntegerField(default=35, verbose_name='Наценка для товаров с себестом более 50к, %')),
                ('MARKUP_30', models.IntegerField(default=40, verbose_name='Наценка для товаров с себестом более 30к, %')),
                ('MARKUP_10', models.IntegerField(default=50, verbose_name='Наценка для товаров с себестом более 10к, %')),
                ('MARKUP_5', models.IntegerField(default=70, verbose_name='Наценка для товаров с себестом более 5к, %')),
                ('MARKUP_2', models.IntegerField(default=90, verbose_name='Наценка для товаров с себестом более 2к, %')),
                ('MARKUP_0', models.IntegerField(default=120, verbose_name='Наценка для товаров с себестом менее 2к, %')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='days_in_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дней на складе'),
        ),
    ]
