# Generated by Django 3.2.16 on 2023-07-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230711_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsettings',
            old_name='DELIVERY_COSTS',
            new_name='delivery_cost',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_0',
            new_name='markup_0',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_10',
            new_name='markup_10',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_100',
            new_name='markup_100',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_2',
            new_name='markup_2',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_30',
            new_name='markup_30',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_5',
            new_name='markup_5',
        ),
        migrations.RenameField(
            model_name='customsettings',
            old_name='MARKUP_50',
            new_name='markup_50',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='EXCHANGE_RATE',
        ),
        migrations.AddField(
            model_name='customsettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5, verbose_name='Биржевой курс валюты (китайский юань)'),
        ),
    ]
