# Generated by Django 3.2.16 on 2023-07-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230711_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsettings',
            name='markup_10',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='markup_100',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='markup_30',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='markup_5',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='markup_50',
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_128',
            field=models.IntegerField(default=25, verbose_name='Наценка для товаров с себестом более 128к, %'),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_16',
            field=models.IntegerField(default=40, verbose_name='Наценка для товаров с себестом более 16к, %'),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_32',
            field=models.IntegerField(default=35, verbose_name='Наценка для товаров с себестом более 32к, %'),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_4',
            field=models.IntegerField(default=70, verbose_name='Наценка для товаров с себестом более 4к, %'),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_64',
            field=models.IntegerField(default=30, verbose_name='Наценка для товаров с себестом более 64к, %'),
        ),
        migrations.AddField(
            model_name='customsettings',
            name='markup_8',
            field=models.IntegerField(default=50, verbose_name='Наценка для товаров с себестом более 8к, %'),
        ),
    ]
