# Generated by Django 4.2.16 on 2024-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_scansnnumber_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sold',
            field=models.BooleanField(blank=True, null=True, verbose_name='Продан'),
        ),
    ]
