# Generated by Django 3.2.16 on 2023-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230711_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='target_price_RUB',
            new_name='target_current_RMB_price_RUB',
        ),
        migrations.AddField(
            model_name='catalog',
            name='target_last_order_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена, руб.'),
        ),
    ]
