# Generated by Django 4.2.16 on 2024-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_goods_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='goods',
            name='defect',
            field=models.BooleanField(blank=True, null=True, verbose_name='Брак'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
    ]
