# Generated by Django 3.2.16 on 2023-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230711_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='order_price_RMB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена закупки в юанях.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='target_current_RMB_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена от курса, руб.'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='target_last_order_price_RUB',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Расчетная цена от последней закупки, руб.'),
        ),
    ]
